version: 2

jobs:
  flake8:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run: python -m pip install flake8
      - run: flake8 {{ cookiecutter.__project_name_snake }}

  prettier:
    docker:
      - image: circleci/node:{{ cookiecutter.node_version }}
    steps:
      - checkout:

      - type: cache-restore
        keys:
          - node-modules-{% raw %}{{ .Branch }}-{{ checksum "package-lock.json" }}{% endraw %}
          - node-modules-{% raw %}{{ .Branch }}-{% endraw %}
          - node-modules-main-

      - run: npm install
      - run: npm run lint

      - type: cache-save
        key: node-modules-{% raw %}{{ .Branch }}-{{ checksum "package-lock.json" }}{% endraw %}
        paths:
          - 'node_modules'

  test:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout

      - type: cache-restore
        keys:
          - pip-{% raw %}{{ .Branch }}-{% endraw %}
          - pip-main-

      - run: python -m pip install flit
      - run: flit install --deps production --extras testing

      - type: cache-save
        key: pip-{% raw %}{{ .Branch }}-{{ epoch }}{% endraw %}
        paths:
          - '~/.cache/pip'

      - run: python testmanage.py test

  nightly-wagtail-test:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run: git clone git@github.com:wagtail/wagtail.git

      - run: python -m pip install flit
      - run: flit install --deps production --extras testing
      - run: python -m pip install ./wagtail

      - run: python testmanage.py test

      - run:
          when: on_fail
          command: python ./.circleci/report_nightly_build_failure.py

workflows:
  version: 2
  test:
    jobs:
      - flake8
      - prettier
      - test

  nightly:
    jobs:
      - nightly-wagtail-test
    triggers:
      - schedule:
          cron: '0 0 * * *'
          filters:
            branches:
              only:
                - main
